[package]
name = "cosmoflow"
version = "0.1.0"
edition = "2024"
authors = ["echozyr2001 <echo.zyr.2001@gmail.com>"]
description = "CosmoFlow - A type-safe workflow engine for Rust, inspired by PocketFlow and optimized for LLM applications"
license = "MIT"
keywords = ["llm", "ai", "workflow", "cosmoai", "flow", "graph"]
homepage = "https://github.com/echozyr2001/CosmoFlow"
repository = "https://github.com/echozyr2001/CosmoFlow"
readme = "../README.md"

[dependencies]
shared_store = { workspace = true }
node = { workspace = true }
action = { workspace = true }
flow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

# Optional dependencies
builtin = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = ["storage-memory"]

# Storage backend features
storage-memory = [
  "shared_store/storage-memory",
  "node/storage-memory",
  "flow/storage-memory",
  "builtin?/storage-memory",
]
storage-file = [
  "shared_store/storage-file",
  "node/storage-file",
  "flow/storage-file",
  "builtin?/storage-file",
]
storage-full = [
  "shared_store/storage-full",
  "node/storage-full",
  "flow/storage-full",
  "builtin?/storage-full",
]

# Optional functionality features
builtin = ["dep:builtin"]
