[package]
name = "cosmoflow"
version = "0.1.0"
edition = "2024"
authors = ["echozyr2001 <echo.zyr.2001@gmail.com>"]
description = "CosmoFlow - A type-safe workflow engine for Rust, inspired by PocketFlow and optimized for LLM applications"
license = "MIT"
keywords = ["llm", "ai", "workflow", "cosmoai", "flow", "graph"]
homepage = "https://github.com/echozyr2001/CosmoFlow"
repository = "https://github.com/echozyr2001/CosmoFlow"
readme = "../README.md"

[dependencies]
flow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }

# Optional dependencies
builtin = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = { workspace = true }

[features]
default = []

# Storage backend features
storage-memory = []
storage-file = []
storage-full = ["storage-memory", "storage-file"]

# Optional functionality features
builtin = ["dep:builtin"]
builtin-full = ["builtin", "storage-full"]

# Convenience meta-features
minimal = []
basic = ["storage-memory"]
standard = ["storage-memory", "builtin"]
full = ["storage-full", "builtin-full"]
