[workspace]
members = ["cosmoflow", "shared_store", "action"]
default-members = ["cosmoflow"]
resolver = "2"

[workspace.dependencies]
# Shared dependencies for workspace members
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tempfile = "3.0"

shared_store = { path = "shared_store" }
