[package]
name = "shared_store"
version = "0.1.0"
edition = "2024"
description = "Storage backends and abstractions for CosmoFlow"

[dependencies]
serde = { workspace = true }

storage = { workspace = true }

[dev-dependencies]

[features]
default = []
