[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmoflow = { path = "../../cosmoflow", features = ["storage-memory"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
